# Deep Learning Course - Requisites Exercises

This is a Jupyter Notebook containing exercises to test the requisites for the Deep Learning course.

### Python

Use Python 3.6 while solving the exercises. We recommend [Anaconda](https://www.continuum.io/downloads) - a Data Science focused python distribution.

### Tools

This is a Jupyter Notebook. If you never used one, a Jupyter notebook is a mix of Markdown (like a Wiki) and a Python program. It is very popular among people working with Data Science and Machine Learning in Python. If you need some help on how to use Jupyter Notebooks, please take a look at this [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

You are free to add as many cells as you want to this notebook in order to make your work readable and well organized.

# Basic Exercises
Let's begin! Start by printing your name and e-mail here:

In [1]:
# fill in your data
print('My name is Solução')
print('My email is ')

My name is Solução
My email is 


## Lists

The following are list exercises. For those that do not have experience with Python, we recommend
using these exercises do learn more about the subject related to the exercise.

In [2]:
mylist = [5, 8, 'abc', 0, 8.3]

### Print the number of elementos of the list `mylist`

In [3]:
print(len(mylist))

5


### Create and print a list with all the even numbers between 0 and 10 inclusive

In [4]:
# there are other solutions
aa = [i for i in range(0,11,2)]
print(aa)

[0, 2, 4, 6, 8, 10]


In [5]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
print(a[3:5])

[3, 4]


In [7]:
# print the odd elements:
print(a[1::2])
# print the even elements:
print(a[::2])
# print the last 3 elements of the list
print(a[-3:])
# print the first 3 elements of the list
print(a[:3])

[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]
[7, 8, 9]
[0, 1, 2]


In [8]:
print(a[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [9]:
# print the odd elements, from the largest to the smallest
print(a[::-2])

[9, 7, 5, 3, 1]


## Tuples

In [10]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


The main difference between a list and a tuple is imutable.

# Exercises with NumPy

The following exercises should use only NumPy operations.
Avoid import other packages

In [11]:
import numpy as np

In [12]:
A = np.arange(10,34).reshape(4,6)
print(A)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


### rows, cols, dimensions, shape and datatype

In [13]:
# print the number of rows of A:
print(A.shape[0])
# print the number of cols of A:
print(A.shape[1])
# print the number of dimensions of A:
print(A.ndim)
# print the shape of A:
print(A.shape)
# print the datatype of the elements of A
print(A.dtype)

4
6
2
(4, 6)
int64


### Boolean array

In [14]:
# create a boolean matrix B with True if the element of A é less than 8 (without using a loop)
B = A < 8 # modify your code here
print(B)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


### Axis reduction: sum

In [15]:
print(A.sum(axis=0))

[76 80 84 88 92 96]


In [16]:
# what is the number of dimensions of the array C = A.sum(axis=0)?
print(A.sum(axis=0).ndim)
# compute the mean value of the array A
print(A.mean())

1
21.5


In [17]:
# create a matrix C that is a normalization of A, so that its value are between 0.0 and 1.0
C = (A - A.min())/(A.max()-A.min())
print(C)

[[ 0.          0.04347826  0.08695652  0.13043478  0.17391304  0.2173913 ]
 [ 0.26086957  0.30434783  0.34782609  0.39130435  0.43478261  0.47826087]
 [ 0.52173913  0.56521739  0.60869565  0.65217391  0.69565217  0.73913043]
 [ 0.7826087   0.82608696  0.86956522  0.91304348  0.95652174  1.        ]]


In [18]:
# create a matrix D that is a nomalization of the columns of A, so that each column of D has values between 0. and 1.
D = (A - A.min(0))/(A.max(0)-A.min(0))
print(D)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667]
 [ 1.          1.          1.          1.          1.          1.        ]]


### Slicing

In [19]:
# this operation is called slicing:
AA = A[:,1::2]
print(AA)

[[11 13 15]
 [17 19 21]
 [23 25 27]
 [29 31 33]]


In [20]:
# create matrix AB with the even rows of matrix A, using the concept of slicing:
AB = A[::2,:]
print(AB)

[[10 11 12 13 14 15]
 [22 23 24 25 26 27]]


### Matrix dot product

In [21]:
# create a matriz AC which is a rotation of 90 degrees clockwise of the matrix A
AC = A[::-1,:].T
print(AC)

[[28 22 16 10]
 [29 23 17 11]
 [30 24 18 12]
 [31 25 19 13]
 [32 26 20 14]
 [33 27 21 15]]


Compute $$ E = \sqrt{ A A^T} $$

In [22]:
E = np.sqrt(A.dot(A.T)) # modify your code here
print(E)

[[ 30.90307428  37.48332963  43.06971093  48.01041554]
 [ 37.48332963  45.50824101  52.31634544  58.33523806]
 [ 43.06971093  52.31634544  60.15812497  67.08949247]
 [ 48.01041554  58.33523806  67.08949247  74.82646591]]


### 3-D array

In [23]:
F = A.reshape(2,3,4)
print(F)

[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]
  [30 31 32 33]]]


In [24]:
# print the number of dimensions of F
print(F.ndim)
# print the shape of F
print(F.shape)
# compute the mean value of the two matrices F[0] and F[1], with a single command using F.mean(??)
print(F.mean((1,2)))

3
(2, 3, 4)
[ 15.5  27.5]


In [25]:
a = np.array([1,2,3,4]).reshape(4,1)
print(a)

[[1]
 [2]
 [3]
 [4]]


### Broadcasting

In [26]:
# Using the concept of broadcasting, create matrix G with the sum of vector a to every column of A:
G = A + a
print(G)

[[11 12 13 14 15 16]
 [18 19 20 21 22 23]
 [25 26 27 28 29 30]
 [32 33 34 35 36 37]]


### Function - one-hot encoding

Define a function that receives as input an one-dimensional array and the output a one-hot encoding
following the example:

In [27]:
# input
aa = np.array([2,0,3,2,1])
print(aa)

[2 0 3 2 1]


In [28]:
# output
oo = np.array([[0,0,1,0],
               [1,0,0,0],
               [0,0,0,1],
               [0,0,1,0],
               [0,1,0,0]])
print(oo)

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [29]:
# Try to avoid explicit loop as much as possible
# Use only NumPy operations, no other libraries
# First Solution
def one_hot(i):
    # insert your code here
    n_samples = i.shape[0]
    n_classes = i.max() + 1
    oh = np.zeros((n_samples,n_classes), dtype=np.int)
    oh[np.arange(n_samples),i] = 1
    return oh

print(one_hot(aa))

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [30]:
# Try to avoid explicit loop as much as possible
# Use only NumPy operations, no other libraries
# Second Solution
def one_hot(i):
    # insert your code here
    n_classes = i.max() + 1
    oh = np.eye(n_classes,dtype=np.int)[i]
    return oh

print(one_hot(aa))

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


# The end