# Curso Deep Learning - Exercício pré-curso Python - NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para familiarizar o participante na linguagem Python para manipulação matricial.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python, consultar
documentação e tutoriais disponíveis na Internet.

Estes exercícios são de dificuldade **intermediária para difícil**, pois a programação matricial não é uma forma
usual de programação, principalmente para quem está acostumado a programar com laços explícitos como num 
programa escrito em C para percorrer todos os elementos de uma matriz. Em Python-NumPy deve-se evitar o uso
de laços explícitos e utilizar operações matriciais. É mais eficiente e deixa o código bem mais compacto.

Não se preocupe caso não consiga fazer todos os exercícios.

### Python

O curso será feito utilizando a versão Python 3.6, assim recomenda-se que estes exercícios sejam feitos com o Python 3.
Recomenda-se instalar o Jupyter e o Python utilizando-se o [Anaconda](https://www.continuum.io/downloads) - uma distribuição
focada em Data Science, contendo os principais pacotes usados nesta área.

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python. Se você precisar de ajuda sobre como usar os Notebooks Jupyter, veja [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios básicos

Vamos começar! Comece imprimindo seu nome e e-mail aqui:

In [1]:
# preencha com seus dados
print('My name is ')
print('My email is ')

My name is 
My email is 


## Listas

Seguem alguns exercícios com lista. Python é muito bom para processar listas. Uma lista é uma sequência de elementos 
separados por vírgula dentro de chaves:

In [2]:
mylist = [5, 8, 'abc', 0, 8.3]

### Imprimindo o número de elementos de uma `mylist` e alguns de seus elementos

In [3]:
print(len(mylist))
print(mylist[0])
print(mylist[-1])  # observe o índice -1 (o que isso significa?)

5
5
8.3


## Seja uma lista de 10 elementos numéricos sequenciais, começando em zero

Aqui será utilizado um for para criar a lista. Este tipo de construção é denominado "List Compreension" ou
"Compreensão de Lista" em portugues. Coloque este termo no Google adicionando python na frente na forma:
"python copreension list" e você poderá ver vários exemplos e tutoriais sobre o assunto.

Neste curso, usaremos muito pouco este recurso pois ele possui um laço explícito para gerar os elementos da
lista. Mais à frente iremos fazer o mesmo exercícios em NumPy utilizando arrays e daí não existirá o laço explícito.

In [4]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Fatiamento em Python

Um conceito fundamental em Python é o do fatiamento "slicing", em inglês. É um conceito que será muito usado
durante todo o curso. Estude bem isso. Inicialmente iremos trabalhar com fatiamento de lista, mas posteriormente
com arrays (ou tensores) utilizando o NumPy

In [5]:
print(a[3:5])

[3, 4]


### Criar e imprimir uma lista a partir da lista "a" já criada, porém apenas alguns elementos

In [6]:
# imprima os elementos ímpares de a
print(a[:])
# imprima os elementos pares de a
print(a[:])
# imprima os últimos 3 elementos da lista (utilize índice negativo, pesquise na Internet)
print(a[:])
# Imprima os 3 primeiros elementos da lista (veja quando é possível ignorar valores iniciais e finais)
print(a[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
# Veja o significado do passo:
print(a[::2])
print(a[::-1])

[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [8]:
# imprima os elementos ímpares na order reversa, do maior para o menor
print(a[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Tuplas

In [9]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


A principal diferença entre uma lista e uma tupla é:

# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

In [10]:
import numpy as np

In [11]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
A = np.arange(24).reshape(4,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### rows, cols, dimensions, shape and datatype

In [13]:
# imprima o número de linhas de A
print()
# imprima o número de colunas de A
print()
# imprima o número de dimensões de A
print()
# imprima o shape de A:
print()
# imprima o tipo de dados (dtype) dos elementos de A:
print()

### Reshape

In [14]:
# Seja o vetor unidimension a:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


In [15]:
# converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape
a = a
print(a)

[1 2 3 4]


## Operações aritméticas

In [16]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

In [17]:
# crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)
C = B # modify your code here
print(C)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


## Indexação booleana

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [18]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Troque o programa acima por uma única linha sem loop

In [19]:
D = B   # << modifique aqui utilizando indexação booleana
print(D)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [20]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[36 40 44 48 52 56]
(6,)


In [21]:
# imprima o número de dimensões do array  As = A.sum(axis=0)?
print()
# calcule o valor médio do array A
print()

$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max}} - A_{min} $$

In [22]:
# Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1
C = A
print(C)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [23]:
# Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A
# de modo que as colunas da matriz D estejam entre os valores de 0 a 1.
# Dica: utilize o conceito de redução de eixo
D = A
print(D)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Fatiamento em arrays (slicing)

In [24]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [25]:
# criar a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:
AB = A
print(AB)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [26]:
# crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa:
# trocando a ordem das linhas e das colunas
AC = A
print(AC)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Produto matricial  (dot product)

Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [27]:
E = A # modify your code here
print(E)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [28]:
# Por que a seguinte operação de multiplicação dá erro?
Ee = A * A.T

ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. Tensorflow usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [ ]:
F = A.reshape(2,3,4)
print(F)

#### Indexação

Estude e explique as seguintes indexações:

In [ ]:
print(F[1])
print(F[1,0])
print(F[1,0,2])

In [ ]:
# imprima o número de dimensões de F
print()
# imprima o shape de F
print()

## Redução de eixo - aplicado a dois eixos simultâneos

In [ ]:
# calcule o valor médio das matrizes F[0] e F[1], com apenas um comando usando F.mean(??)
print()

## Broadcasting

O que significa o conceito de broadcasting em NumPy?

In [ ]:
# Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer em G = A + a
a = np.arange(4)
print(a)
#G = A + a
#print(G)

## Function - one-hot encoding

Defina uma função que receba como entrada um array unidimensional e gere como saída o
array na codificação one-hot, conforme exemplo a seguir:

In [29]:
# Entrada, vetor de 5 elementos representando classes
aa = np.array([2,0,3,2,1])
print(aa)

[2 0 3 2 1]


In [30]:
# Saída da função oo = one_hot(aa)
oo = np.array([[0,0,1,0],
               [1,0,0,0],
               [0,0,0,1],
               [0,0,1,0],
               [0,1,0,0]])
print(oo)

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [31]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def one_hot(i):
    # insert your code here
    oh = i
    return oh

print(one_hot(aa))

[2 0 3 2 1]


In [32]:
# Try to avoid explicit loop as much as possible
# Use only NumPy operations, no other libraries
# Second Solution
def one_hot(i):
    # insert your code here
    n_classes = i.max() + 1
    oh = np.eye(n_classes,dtype=np.int)[i]
    return oh

print(one_hot(aa))

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [33]:
# Teste sua função com outros valores

# Fim do notebook