# NumPy: *broadcasting*, *reshape* e redução de eixo

Entender o funcionamneto do *broadcasting*,  *reshape* e do *axis* do NumPy é muito importante. Nesse tutorial iremos ilustrar esses conceitos através de exemplos. 

## Reshape

In [2]:
import numpy as np

a = np.arange(10)
print "a:"
print a
print "A eh um array unidimensional, a.shape=", a.shape

a:
[0 1 2 3 4 5 6 7 8 9]
A eh um array unidimensional, a.shape= (10,)


Podemos utilizar o reshape para "enxergar" o array *a* como um array bidimensional com uma linha.

Quando o valor da dimensão for -1, significa que será utilizado o valor que falta para que o reshape fique correto. Por exemplo no exemplo a seguir, o array "a" possui 10 elementos. Se um dos valores do shape for 1, o valor -1 terá o significado do valor 10:

In [3]:
a = a.reshape(1,-1) # O -1 é uma diretiva para que o NumPy calcule automaticamente as dimensões que faltam
print "a:"
print a
print "A eh um array bidimensional linha, a.shape:", a.shape

a:
[[0 1 2 3 4 5 6 7 8 9]]
A eh um array bidimensional linha, a.shape: (1, 10)


Podemos enxergar o array *a* como um array com uma coluna:

In [4]:
a = a.reshape(-1,1) 
print "a:"
print a
print "A eh um array bidimensional coluna, a.shape:", a.shape

a:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
A eh um array bidimensional coluna, a.shape: (10, 1)


O então como um array bidimensional, desde que o número de elementos do array não exceda o número de elementos do array inicial.

In [5]:
a = a.reshape(5,-1) 
print "a:"
print a
print "A eh um array bidimensional, a.shape:", a.shape

a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
A eh um array bidimensional, a.shape: (5, 2)


## Redução de eixo

Existem várias operações no NumPy que permitem operar ao longo de eixos (colunas ou linhas ou eixos de maiores dimensões). Por exemplo, pode-se 
calcular estatísticas ao longo de um eixo. 
Um array unidimensional possui apenas um eixo (eixo 0), um array bidimensional possui dois eixos (eixos 0 e 1) e assim por diante. Muitas funções do NumPy possuem o parâmetro `axis` que indica se a operação feita para a função será aplicada ao longo de um eixo. Vejo o exemplo da média abaixo:


In [9]:
a = np.arange(18).reshape(3,6)
print 'a:\n',a
print 'a.shape:',a.shape
print 'a.max():',a.max()
print 'a.max(axis=0):', a.max(axis=0)
print 'a.max(axis=0).shape:',a.max(axis=0).shape
print 'a.max(axis=1):', a.max(axis=1)
print 'a.max(axis=1).shape:',a.max(axis=1).shape

a:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
a.shape: (3, 6)
a.max(): 17
a.max(axis=0): [12 13 14 15 16 17]
a.max(axis=0).shape: (6,)
a.max(axis=1): [ 5 11 17]
a.max(axis=1).shape: (3,)


Note que `a.max(0)` opera no eixo das linhas (pois é o primeiro eixo deste array), resultando o valor máximo de cada coluna. O resultado possui 6 elementos que é o número de colunas de a. Note que o shape foi reduzido de (3,6) para (6,), pois a operação se deu na dimensão 0 e o novo array tem uma dimensão a menos, daí o nome da operação de "redução de eixo".

Já o `a.max(1)` opera na direção do eixo nas colunas (segundo eixo na matriz bidimensional), resultando o máximo em cada linha. O shape reduziu de (3,6) para (3,).

## Broadcasting

Nas operações em arrays como a soma entre A e B, é importante que o shape dos dois *arrays* sejam iguais. Existe a exceção que é quando é possível ocorrer a operação de broadcast.

O broadcasting é uma técnica extremamente eficiente que permite processar *arrays* de dimensões diferentes, fazendo a propagação (cópia) do valor de um eixo de um elemento para o número de elemento do outro array.

O broadcast pode acontecer sempre que o array possuir alguma dimensão com apenas 1 elemento.

Vejamos primeiro um exemplo de soma de dois arrays de shapes iguais a (2,5):

In [18]:
A = np.arange(10).reshape(2,5)
B = np.ones(shape=(2,5),dtype=int)
print 'A=\n', A
print 'B=\n', B
print 'A+B=\n',A+B

A=
[[0 1 2 3 4]
 [5 6 7 8 9]]
B=
[[1 1 1 1 1]
 [1 1 1 1 1]]
A+B=
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Agora, o array B terá dimensões (2,1), terá apenas uma coluna. Como a soma se dará entre o array A com shape (2,5) somado ao array com shape (2,1), este último array é *broadcast* para (2,5) internamente de forma eficiente e o resultado será igual ao anterior:

In [19]:
A = np.arange(10).reshape(2,5)
B = np.ones(shape=(2,1),dtype=int)
print 'A=\n', A
print 'B=\n', B
print 'A+B=\n',A+B

A=
[[0 1 2 3 4]
 [5 6 7 8 9]]
B=
[[1]
 [1]]
A+B=
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


É possível também que o broadcast aconteça nos dois arrays da operação, de forma simultânea. Por exemplo podemos ter dois arrays bidimensionais um com dimensões (2,1) e outro com dimensões (1,5). O broadcast entre os dois será possível e o resultado será shape (2,5):

In [20]:
A = np.arange(5).reshape(1,5)
B = np.ones(shape=(2,1),dtype=int)
print 'A=\n', A
print 'B=\n', B
print 'A+B=\n',A+B

A=
[[0 1 2 3 4]]
B=
[[1]
 [1]]
A+B=
[[1 2 3 4 5]
 [1 2 3 4 5]]


## Combinando a redução de eixo com broadcast

É comum utilizar o broadcast de um array com a redução de eixo produzindo operações bastante eficientes. Por exemplo queremos que, dada uma matriz bidimensional, cada linha seja dividida pelo valor máximo da linha, de modo que cada linha seja normalizada.

É possível primeiro fazer a redução do eixo, calculando o máximo em cada linha (eixo 1) e depois fazer o broadcast pela divisão do array pelo array de máximo.

In [26]:
A = np.arange(20).reshape(4,5).astype(float)
Am = A.max(1, keepdims=True)
B = A/Am
print 'A.shape:',A.shape
print 'A:\n', A
print 'Am.shape:',Am.shape
print 'Am:\n', Am
print 'B.shape:',B.shape
print 'B:\n',B


A.shape: (4, 5)
A:
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]]
Am.shape: (4, 1)
Am:
[[  4.]
 [  9.]
 [ 14.]
 [ 19.]]
B.shape: (4, 5)
B:
[[ 0.          0.25        0.5         0.75        1.        ]
 [ 0.55555556  0.66666667  0.77777778  0.88888889  1.        ]
 [ 0.71428571  0.78571429  0.85714286  0.92857143  1.        ]
 [ 0.78947368  0.84210526  0.89473684  0.94736842  1.        ]]
