# Curso Deep Learning - Exercício pré-curso Python - NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para familiarizar o participante na linguagem Python para manipulação matricial.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python, consultar documentação e tutoriais disponíveis na Internet.

Estes exercícios são de dificuldade **intermediária para difícil**, usaremos programação
avançada Python, explorando listas, dicionários, programação matricial e programação
orientada a objeto.

### Python

O curso será feito utilizando a versão Python 3.6, assim recomenda-se que estes exercícios sejam feitos com o Python 3.
Recomenda-se instalar o Jupyter e o Python utilizando-se o [Anaconda](https://www.continuum.io/downloads) - uma distribuição
focada em Data Science, contendo os principais pacotes usados nesta área.

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python. Se você precisar de ajuda sobre como usar os Notebooks Jupyter, veja [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

Instale o Jupyter nbextensions que é um conjunto de ferramentas auxiliares. Habilite o "Table of Contents" do nbextensions para que este notebook fique itemizado.

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios básicos

Vamos começar! Comece imprimindo seu nome e e-mail aqui:

In [1]:
# preencha com seus dados
print('My name is ')
print('My email is ')

My name is 
My email is 


## Listas

Iremos utilizar muitas listas no curso Deep Learning.
Seguem alguns exercícios com lista. Python é muito bom para processar listas. Uma lista é uma sequência de elementos 
separados por vírgula dentro de chaves:

In [2]:
mylist = [5, 8, 'abc', 0, 8.3]

### Imprimindo o número de elementos de uma `mylist` e alguns de seus elementos

In [3]:
print(len(mylist))
print(mylist[0])
print(mylist[-1])  # observe o índice -1 (o que isso significa?)

5
5
8.3


## Seja uma lista de 10 elementos numéricos sequenciais, começando em zero

O código a seguir é típico para criar uma lista com os 10 primeiros inteiros maiores ou iguais a zero: inicializa-se lista vazia, para cada i entre 0 e menor que 10, faz append na lista a:

In [4]:
a = []
for i in range(10):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## List Comprehension

Esta mesma lista pode ser criada utilizando a construção denominada "List Comprehension" ou
"Compreensão de Lista" em portugues. Coloque este termo no Google adicionando python na frente na forma:
"python comprehension list" e você poderá ver vários exemplos e tutoriais sobre o assunto. É uma forma compacta que fazer um append iterativo numa lista:

Veja como o trecho acima foi reduzido para uma linha apenas:

In [5]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
new_list = []
for k,i in enumerate(m_list):
    new_list.append(str(k)+i)
print(new_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


- Explique o que o enumerate faz no programa acima:
- Repita o mesmo exercício de criar a lista new_list, porém utilizando list comprehension:
   

In [7]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
n_list = [] # utilize aqui o list comprehension

## Fatiamento em Python

Um conceito fundamental em Python é o do fatiamento "slicing", em inglês. É um conceito que será muito usado
durante todo o curso. Estude bem isso. Inicialmente iremos trabalhar com fatiamento de lista, mas posteriormente
com arrays (ou tensores) utilizando o NumPy

In [8]:
print(a[3:5])

[3, 4]


### Criar e imprimir uma lista a partir da lista "a" já criada, porém apenas alguns elementos

In [9]:
# imprima os elementos ímpares de a
print(a[:])
# imprima os elementos pares de a
print(a[:])
# imprima os últimos 3 elementos da lista (utilize índice negativo, pesquise na Internet)
print(a[:])
# Imprima os 3 primeiros elementos da lista (veja quando é possível ignorar valores iniciais e finais)
print(a[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
# Veja o significado do passo:
print(a[::2])
print(a[::-1])

[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [11]:
# imprima os elementos ímpares na order reversa, do maior para o menor
print(a[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Tuplas

Dominar o conceito de tuplas é importante pois tuplas são estruturas muito utilizadas no Python.

In [12]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


A principal diferença entre uma lista e uma tupla é:

# Dicionários em Python

Python possui uma estrutura de dados muito versátil denominada dicionário.
No curso Deep Learning, os parâmetros da rede neural serão armazenadas na forma de dicionário.

In [13]:
rob_record = {'nome': 'Roberto', 'idade': 18}
print(rob_record['nome'])

Roberto


In [14]:
rob_record['idade'] = 20
print(rob_record)

{'nome': 'Roberto', 'idade': 20}


Lista de dicionários:

In [15]:
records = [{'nome':'Alfredo', 'idade': 23},
           {'nome':'Fernanda', 'idade': 16},
           {'nome':'Carla', 'idade':33}]

In [16]:
# acesse o nome da Fernanda: complete e descomente a linha a seguir
#print(records[][])

In [17]:
# crie uma lista com todos os nomes da lista records.
# resultado deve ser uma lista ['Alfredo', 'Fernanda', 'Carla']
# 1. Utilizando a forma tradicional de criar lista com append
nlist = []
#for  :
#    nlist.append()
print(nlist)

[]


In [18]:
# 2. Utilizando a forma de list comprehension
#nlist2 = [ for ]
#print(nlist2)

# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote que ter o Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

In [19]:
import numpy as np

In [20]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
A = np.arange(24).reshape(4,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### rows, cols, dimensions, shape and datatype

In [22]:
# imprima o número de linhas de A
print()
# imprima o número de colunas de A
print()
# imprima o número de dimensões de A
print()
# imprima o shape de A:
print()
# imprima o tipo de dados (dtype) dos elementos de A:
print()

### Reshape

In [23]:
# Seja o vetor unidimension a:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


In [24]:
# converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape
a = a
print(a)

[1 2 3 4]


## Operações aritméticas

In [25]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

In [26]:
# crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)
C = B # modify your code here
print(C)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


## Indexação booleana

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [27]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Troque o programa acima por uma única linha sem loop

In [28]:
D = B   # << modifique aqui utilizando indexação booleana
print(D)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [29]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[36 40 44 48 52 56]
(6,)


In [30]:
# imprima o número de dimensões do array  As = A.sum(axis=0)?
print()
# calcule o valor médio do array A
print()

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

In [31]:
# Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1
C = A
print(C)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [32]:
# Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A
# de modo que as colunas da matriz D estejam entre os valores de 0 a 1.
# Dica: utilize o conceito de redução de eixo
D = A
print(D)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Fatiamento em arrays (slicing)

In [33]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [34]:
# criar a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:
AB = A
print(AB)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [35]:
# crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa:
# trocando a ordem das linhas e das colunas
AC = A
print(AC)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Produto matricial  (dot product)

Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [36]:
E = A # modify your code here
print(E)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [37]:
# Descomente a linha e explique
# por que a operação de multiplicação dá erro?
#Ee = A * A.T

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [38]:
F = A.reshape(2,3,4)
print(F)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Indexação

Estude e explique as seguintes indexações:

In [39]:
print(F[1])
print(F[1,0])
print(F[1,0,2])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[12 13 14 15]
14


In [40]:
# imprima o número de dimensões de F
print()
# imprima o shape de F
print()

## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

In [41]:
# calcule o valor médio das matrizes F[0] e F[1], com apenas um comando usando F.mean(??)
print()

## Broadcasting

O que significa o conceito de broadcasting em NumPy?

In [42]:
# Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer em G = A + a
a = np.arange(4)
print(a)
#G = A + a
#print(G)

[0 1 2 3]


## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento contrá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [43]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [44]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [45]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [46]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    # insert your code here
    train = val = 0
    return train, val

t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

t=
 0
v=
 0


In [47]:
# Teste sua função com outros valores

# Programação Orientada a Objetos

Documentação oficial: https://docs.python.org/3/tutorial/classes.html

Forma clássica de definição de uma função:

In [48]:
data = np.array([13, 63, 5, 378, 58, 40])

def avg(d):
    return sum(d)/len(d)
    
avg(data)

92.833333333333329

## Definição da classe, variáveis, inicialização e método

Definição da classe `MyAvg`, contendo duas variávels: `id` (compartilhada) e `d`; inicialização e método `avg`.

- **Classe** é uma forma de definir um tipo abstrato de dados
- **Instância** de uma classe é chamada **objeto**
- Operadores ou funções de uma classe são chamados **métodos**
- **Variáveis de instância** são variáveis associadas à instância
- **Variáveis de classe** são variáveis compartilhada com todas as instâncias da classe

O nome de uma classe é usualmente escrita usando *Camel case* enquanto que métodos são
escritos com caixa baixa.

In [49]:
class MyAvg:
    id = 0.33                # variável compartilhada com todas as instâncias
    
    def __init__(self,data):
        self.d = data        # variável associada a cada instância 
        
    def avg(self): # método para calcular a média
        return sum(self.d)/len(self.d)

Objetos `a` e `b` são instâncias da classe `MyAvg`.
Instanciar uma classe é inicializá-la através da chamada ao método __init__:

In [50]:
a = MyAvg(data)
b = MyAvg(2*data)

Aplicação do método `avg()`, retorna a média dos dados dos objetos a e b:

In [51]:
print(a.avg())
print(b.avg())

92.8333333333
185.666666667


In [52]:
# Imprima os valores dos dados associados aos objetos a e b:
print(a)
print(b)

In [53]:
# Imprima a variável compartilhada `id` de cada objeto a e b:
print(a)
print(b)

## Herança de classe

In [54]:
class MyAvgStd(MyAvg):
    def var(self): # método adicional para calcular a variância
        u = self.avg()
        return np.sqrt(np.sum((self.d - u)**2)/len(self.d))

In [55]:
c = MyAvgStd(data)

In [56]:
print('media:',c.avg())
print('variancia:',c.var())

media: 92.8333333333
variancia: 129.29477518


In [57]:
# imprima os dados associados ao objeto c e a sua variável compartilhada id

### Exercício: convertendo a função `split` na classe `C_Split`

Implemente a classe `C_Split` para ter a mesma funcionalidade da função `split` feita acima

In [58]:
class C_Split():
    def __init__(self,d):
        pass
    def split(self, split_factor ):
        pass

In [59]:
#data_train_val = C_Split(aa)
#train, val = data_train_val.split(0.8)

## Classe com métodos `__len__` e `__getitem__`

Uma classe com métodos `__len__` e `__getitem__` permite que os objetos possam ser indexados e calculado o seu número de elementos.

Veja o exemplo a seguir:

In [60]:
class Word():
    def __init__(self, phrase):
        self.wordlist = phrase.split() # separa frase em uma lista de palavras
    
    def __len__(self):
        return len(self.wordlist)
    
    def __getitem__(self,x):
        return self.wordlist[x]

In [61]:
frase = 'Esta frase é formada por 7 palavras'
palavras = Word(frase)

In [62]:
palavras[3]  # permite a indexação do objeto

'formada'

In [63]:
print(len(palavras))

7


### Exercício para indexar elementos de um dicionário

Um dicionário em Python não é indexado. Por exemplo seja o dicionário `d` a seguir.
Não é possível indexar d[0] ou d[1] para buscar o primeiro ou segundo par (chave:valor).

In [64]:
d = {'a':1,'b': 2}

Implementar uma classe que receba um dicionário e permita que ele possa ser indexado.
Para converter um dicionário em uma lista de pares, use:

In [65]:
list(d.items())

[('a', 1), ('b', 2)]

Complete a definição da classe `dicdata` a seguir para que um dicionário possa ser
indexado:

In [66]:
class DicData():
    def __init__(self, dic):
        print('a definir')
        
    def __len__(self):
        print('a definir')
        
    def __getitem__(self):
        print('a definir')

In [67]:
dd = DicData(d)
#print(len(dd))
#print(dd[0])

a definir


## Iteradores

Iteradores são uteis para serem usados em estruturas do tipo `for a in b:`.

Listas em Python são consideradas iteráveis, pois podem ser utilizadas nessa estrutura:

In [68]:
for i in ['a', 'b', 'c']:
    print(i)

a
b
c


O método do `range()` do python também é um iterável:

In [69]:
for i in range(3):
    print(i)

0
1
2


É possível acessar o iterador destas estruturas utilizando o método `iter()` do Python e então é possível percorrer seus elementos utilizado `next()`:

In [70]:
lista = ['a', 'b', 'c']
iterador = iter(lista)
print('tipo de iterador:', type(lista))
print('tipo de iterador:', type(iterador))
print(next(iterador))

tipo de iterador: <class 'list'>
tipo de iterador: <class 'list_iterator'>
a


O acesso de iteradores é sequencial e após o ultimo elemento uma exceção é levantada indicando o fim do iterador.
Descomente o último `next` e veja o tipo da exceção que acontece.

In [71]:
print(next(iterador))
print(next(iterador))
#print(next(iterador))

b
c


## Criando objetos iteráveis

Para implementar um objeto iterador é preciso escrever um método `__next__()` para a classe e para que ele seja acessível como iterável também é necessário escrever um método `__iter__()`: 

In [72]:
class WordIterator():
    def __init__(self, phrase):
        self.words = phrase.split()
        
    def __iter__(self):
        self.iter_index = 0
        return self
    
    def __next__(self):
        if self.iter_index < len(self.words):
            i = self.iter_index
            self.iter_index += 1
            return self.words[i]
        else:
            raise StopIteration()

A classe acima é um iterador e é iterável. 

No método `__iter__()` reiniciamos o índice inicial para o iterador e retornamos o próprio objeto (um iterador).

No método `__next__()` retornamos a palavra do índice atual ou a exceção de parada, caso seja o fim.

In [73]:
frase = 'Esta frase é formada por 7 palavras'
iterador_de_palavras = WordIterator(frase)

In [74]:
for palavra in iterador_de_palavras:
    print(palavra)

Esta
frase
é
formada
por
7
palavras


### Exercício com iterador

Crie uma classe `DictIterator` que permita varrer os itens de um dicionário utilizando o `for`

In [75]:
class DictIterator():
    def __init__(self, dict):
        print('a definir')
    def __iter__(self):
        print('a definir')
    def __next__(self):
        print('a definir')

In [76]:
d = {'a':1,'b': 2, 'c': 3}
d_iter = DictIterator(d)
#for i in d_iter:
#    print(i)

a definir


## Objeto como função

É possível declarar uma classe contendo um objeto possa ser chamado (*callable object*).
Para isso, a classe deve conter o método `__call__`. Veja o exemplo a seguir:

In [77]:
class Scale():
    def __init__(self, w):
        self._w = w
    def __call__(self, x):
        return x * self._w

In [78]:
s = Scale(100.)
print(s(5))


500.0


### Exercício de classe contendo objeto chamável

Defina uma classe herdada da classe `Scale` que permita modificar a variável `self._w`.

In [79]:
class AjustaPeso(Scale):
    def wset():
        print('a preencher')

In [80]:
ap = AjustaPeso(100.)
print(ap(5))

500.0


In [81]:
#ap.wset(10)
#print(ap(5))

# Fim do notebook