# Matrizes, Arrays, Tensores

## Referências

- Documentação oficial de Tensores do PyTorch
    http://pytorch.org/docs/master/tensors.html
- PyTorch para usuários NumPy:
    https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

## NumPy array

In [0]:
import numpy as np

In [62]:
a = np.array([[2., 8., 3.],
              [0.,-1., 5.]])
a

array([[ 2.,  8.,  3.],
       [ 0., -1.,  5.]])

In [63]:
a.shape

(2, 3)

In [64]:
a.dtype

dtype('float64')

## PyTorch tensor

Os tensores do PyTorch só podem ser float, float32 ou float64

In [0]:
import torch

### Convertendo NumPy array para tensor PyTorch

In [66]:
b = torch.Tensor(np.zeros((3,4)))
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Criando arrays e tensores constantes

In [67]:
c = np.ones((2,4)); c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
d = torch.ones((2,4)); d

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Criando arrays e tensores aleatórios

In [69]:
e = np.random.rand(2,4); e

array([[0.95813935, 0.87593263, 0.35781727, 0.50099513],
       [0.68346294, 0.71270203, 0.37025075, 0.56119619]])

In [70]:
f = torch.rand(2,4); f

tensor([[0.6738, 0.3315, 0.7837, 0.5631],
        [0.7749, 0.8208, 0.2793, 0.6817]])

### Arrays aleatórios com semente, para reproduzir mesma sequência pseudoaleatória

In [71]:
np.random.seed(1234)
e = np.random.rand(2,4);e

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858],
       [0.77997581, 0.27259261, 0.27646426, 0.80187218]])

In [72]:
torch.manual_seed(1234)
f = torch.rand(2,4); f

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681]])

### Torch seed is different for GPU

In [73]:
if torch.cuda.is_available():
    torch.cuda.torch.manual_seed(1234)
    g = torch.cuda.torch.rand(2,4)
    print(g)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681]])


## Conversões entre NumPy e Tensores PyTorch

### NumPy para Tensor PyTorch utilizando `.from_numpy()`

Os tipos de elementos do array NumPy podem ser convertidos 
para tensores equivalentes em PyTorch

In [74]:
import pandas as pd 
dtypes = [np.uint8, np.int32, np.int64, np.float32, np.float64, np.double]
table = np.empty((2, len(dtypes)),dtype=np.object)
for i,t in enumerate(dtypes):
    a = np.array([1],dtype=t)
    ta = torch.from_numpy(a)
    table[0,i] = a.dtype
    table[1,i] = ta.dtype
pd.DataFrame(table)

0            1  ...              4              5
0        uint8        int32  ...        float64        float64
1  torch.uint8  torch.int32  ...  torch.float64  torch.float64

[2 rows x 6 columns]

### NumPy para Tensor utilizando `torch.FloatTensor()` - método recomendado

Existe uma cuidado importante a ser tomado na transformação de matrizes do NumPy para tensores PyTorch pois as funções de rede neurais do PyTorch utilizam o tipo FloatTensor e o NumPy utiliza como default o tipo float64, o que faz uma conversão automática para DoubleTensor do PyTorch e consequentemente gerando um erro.
A recomendação é utilizar o `torch.FloatTensor` para converter NumPy para tensores PyTorch:

In [75]:
a = np.ones((2,5))
print('NumPy', a, a.dtype)
at = torch.FloatTensor(a)
print('PyTorch', at, at.dtype)

NumPy [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64
PyTorch tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) torch.float32


### Tensor PyTorch para array NumPy

In [76]:
ta = torch.ones(2,3)
ta

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [77]:
a = ta.numpy()
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

## Tensor na CPU e na GPU

In [78]:
ta_cpu = torch.ones(2,3); ta_cpu

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [79]:
if torch.cuda.is_available():
    ta_gpu = ta_cpu.cuda()
    print(ta_gpu)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


## Operações em tensores

### criação de tensor e visualização do seu shape

A cada nova versão do PyTorch, ele fica mais compatível com o NumPy. Inicialmente a operação PyTorch equivalente ao shape era apenas o Size. Agora o PyTorch suporta os dois, tanto Size como shape.



In [80]:
a = torch.eye(4); a

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [81]:
a.shape

torch.Size([4, 4])

### Reshape é feito com `view` em PyTorch

In [82]:
b = a.reshape(2,8); b

tensor([[1., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 1.]])

Aqui é um exemplo criando um tensor unidimensional sequencial de 0 a 23 e em seguida uma reshape para
que o tensor fique com 4 linhas e 6 colunas

In [83]:
a = torch.arange(0,24).view(4,6);a

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

### Adição elemento por elemento

#### usando operadores

In [84]:
c = a + a; c

tensor([[ 0,  2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32, 34],
        [36, 38, 40, 42, 44, 46]])

In [85]:
d = a - c ; d

tensor([[  0,  -1,  -2,  -3,  -4,  -5],
        [ -6,  -7,  -8,  -9, -10, -11],
        [-12, -13, -14, -15, -16, -17],
        [-18, -19, -20, -21, -22, -23]])

#### forma funcional

In [86]:
d = a.sub(c); d

tensor([[  0,  -1,  -2,  -3,  -4,  -5],
        [ -6,  -7,  -8,  -9, -10, -11],
        [-12, -13, -14, -15, -16, -17],
        [-18, -19, -20, -21, -22, -23]])

#### Operação in-place
É possível otimizar bastante as expressões em PyTorch utilizando in-place. Entretanto, operações in-place precisam ser feitas com maior cuidado.

In [87]:
a.sub_(c); a

tensor([[  0,  -1,  -2,  -3,  -4,  -5],
        [ -6,  -7,  -8,  -9, -10, -11],
        [-12, -13, -14, -15, -16, -17],
        [-18, -19, -20, -21, -22, -23]])

### Multiplicação elemento por elemento

In [88]:
d = a * c; d 

tensor([[    0,    -2,    -8,   -18,   -32,   -50],
        [  -72,   -98,  -128,  -162,  -200,  -242],
        [ -288,  -338,  -392,  -450,  -512,  -578],
        [ -648,  -722,  -800,  -882,  -968, -1058]])

In [89]:
d = a.mul(c); d

tensor([[    0,    -2,    -8,   -18,   -32,   -50],
        [  -72,   -98,  -128,  -162,  -200,  -242],
        [ -288,  -338,  -392,  -450,  -512,  -578],
        [ -648,  -722,  -800,  -882,  -968, -1058]])

In [90]:
a.mul_(c); a

tensor([[    0,    -2,    -8,   -18,   -32,   -50],
        [  -72,   -98,  -128,  -162,  -200,  -242],
        [ -288,  -338,  -392,  -450,  -512,  -578],
        [ -648,  -722,  -800,  -882,  -968, -1058]])

### Média em tensores

In [91]:
a = torch.arange(0,24,dtype=torch.float32).view(4,6); a

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])

In [92]:
u = a.mean(); u

tensor(11.5000)

In [93]:
uu = a.sum()/a.nelement(); uu

tensor(11.5000)

### Média com redução de eixo 

In [94]:
u_row = a.mean(dim=1); u_row, u_row.shape

(tensor([ 2.5000,  8.5000, 14.5000, 20.5000]), torch.Size([4]))

In [95]:
u_col = a.mean(dim=0); u_col, u_col.shape

(tensor([ 9., 10., 11., 12., 13., 14.]), torch.Size([6]))

### Desvio padrão

In [96]:
std = a.std(); std

tensor(7.0711)

In [97]:
std_row = a.std(dim=1); std_row, std_row.shape

(tensor([1.8708, 1.8708, 1.8708, 1.8708]), torch.Size([4]))

## Comparação speedup CPU e GPU

In [98]:
a_numpy_cpu = np.ones((10,1000,1000),dtype=np.float32)
%timeit b = 2 * a_numpy_cpu
a_torch_cpu = torch.ones(10,1000,1000, dtype=torch.float32)
%timeit b = 2 * a_torch_cpu

100 loops, best of 3: 10.8 ms per loop
100 loops, best of 3: 11.2 ms per loop


In [99]:
if torch.cuda.is_available():
    a_torch_gpu = a_torch_cpu.cuda()
    %timeit b = 2 * a_torch_gpu

10000 loops, best of 3: 539 µs per loop


Rodando o código abaixo na GTX1080: speedup de 15,5
- 888 µs ± 43.4 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
- 57.1 µs ± 22.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Rodando no macbook:
- numpy: 1000 loops, best of 3: 449 µs per loop
- torch: 1000 loops, best of 3: 1.6 ms per loop

In [100]:
%timeit b1 = a_numpy_cpu.mean()
%timeit b2 = a_torch_cpu.mean()
if torch.cuda.is_available():
    %timeit c = a_torch_gpu.mean()

100 loops, best of 3: 4.62 ms per loop
1000 loops, best of 3: 1.51 ms per loop
10000 loops, best of 3: 318 µs per loop
