# Matrizes, Arrays, Tensores

## Referências

- PyTorch para usuários NumPy:
    https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

## NumPy array

In [1]:
import numpy as np

In [2]:
a = np.array([[2., 8., 3.],
              [0.,-1., 5.]])
a

array([[ 2.,  8.,  3.],
       [ 0., -1.,  5.]])

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('float64')

## PyTorch tensor

Os tensores do PyTorch só podem ser float, float32 ou float64

In [5]:
import torch

### Convertendo NumPy array para tensor PyTorch

In [6]:
b = torch.Tensor(a)
b


 2  8  3
 0 -1  5
[torch.FloatTensor of size 2x3]

### Criando arrays e tensores constantes

In [7]:
c = np.ones((2,4)); c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [8]:
d = torch.ones((2,4)); d


 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 2x4]

### Criando arrays e tensores aleatórios

In [9]:
e = np.random.rand(2,4); e

array([[ 0.30518012,  0.6808353 ,  0.31033947,  0.60907142],
       [ 0.75628457,  0.92031815,  0.59122575,  0.35233973]])

In [10]:
f = torch.rand(2,4); f


 0.8897  0.1412  0.9843  0.4037
 0.2441  0.5125  0.4261  0.9143
[torch.FloatTensor of size 2x4]

### Arrays aleatórios com semente, para reproduzir mesma sequência pseudoaleatória

In [11]:
np.random.seed(1234)
e = np.random.rand(2,4);e

array([[ 0.19151945,  0.62210877,  0.43772774,  0.78535858],
       [ 0.77997581,  0.27259261,  0.27646426,  0.80187218]])

In [12]:
torch.manual_seed(1234)
f = torch.rand(2,4); f


 0.1915  0.4977  0.6221  0.8178
 0.4377  0.6121  0.7854  0.7714
[torch.FloatTensor of size 2x4]

### Torch seed is different for GPU

In [45]:
if torch.cuda.is_available():
    torch.cuda.torch.manual_seed(1234)
    g = torch.cuda.torch.rand(2,4)
    print(g)


 0.1915  0.4977  0.6221  0.8178
 0.4377  0.6121  0.7854  0.7714
[torch.FloatTensor of size 2x4]



## Conversões entre NumPy e Tensores PyTorch

### NumPy para Tensor PyTorch

Não são todos os tipos de elementos do array NumPy que podem ser convertidos 
para tensores PyTorch. Abaixo é um programa que cria uma tabela de equivalencias
entre os tipos do NumPy e os tipos do Tensor PyTorch:

In [31]:
import pandas as pd 
dtypes = [np.uint8, np.int32, np.int64, np.float32, np.float64, np.double]
table = np.empty((2, len(dtypes)),dtype=np.object)
for i,t in enumerate(dtypes):
    a = np.array([1],dtype=t)
    ta = torch.from_numpy(a)
    table[0,i] = a.dtype.name
    table[1,i] = type(ta).__name__
pd.DataFrame(table)

0          1           2            3             4             5
0       uint8      int32       int64      float32       float64       float64
1  ByteTensor  IntTensor  LongTensor  FloatTensor  DoubleTensor  DoubleTensor

### Tensor PyTorch para array NumPy

In [33]:
ta = torch.ones(2,3)
print(type(ta).__name__)

FloatTensor


In [34]:
a = ta.numpy()
print(type(a).__name__,a.dtype)

ndarray float32


## Tensor na CPU e na GPU

In [49]:
ta_cpu = torch.ones(2,3); ta_cpu


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

In [52]:
if torch.cuda.is_available():
    ta_gpu = ta_cpu.cuda()
    print(ta_gpu)


 1  1  1
 1  1  1
[torch.cuda.FloatTensor of size 2x3 (GPU 0)]



## Operações em tensores

### criação de tensor e visualização do seu shape

In [37]:
a = torch.eye(4); a


 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1
[torch.FloatTensor of size 4x4]

In [38]:
a.size()

torch.Size([4, 4])

### Reshape é feito com `view` em PyTorch

In [39]:
b = a.view(2,8); b


    1     0     0     0     0     1     0     0
    0     0     1     0     0     0     0     1
[torch.FloatTensor of size 2x8]

Aqui é um exemplo criando um tensor unidimensional sequencial de 0 a 23 e em seguida uma reshape para
que o tensor fique com 4 linhas e 6 colunas

In [64]:
a = torch.arange(0,24).view(4,6);a


  0   1   2   3   4   5
  6   7   8   9  10  11
 12  13  14  15  16  17
 18  19  20  21  22  23
[torch.FloatTensor of size 4x6]

### Adição elemento por elemento

#### usando operadores

In [40]:
c = a + a; c


 2  0  0  0
 0  2  0  0
 0  0  2  0
 0  0  0  2
[torch.FloatTensor of size 4x4]

In [41]:
d = a - c ; d


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

#### forma funcional

In [42]:
d = a.sub(c); d


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

#### Operação in-place

In [43]:
a.sub_(c); a


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

### Multiplicação elemento por elemento

In [44]:
d = a * c; d 


-2  0  0  0
 0 -2  0  0
 0  0 -2  0
 0  0  0 -2
[torch.FloatTensor of size 4x4]

In [45]:
d = a.mul(c); d


-2  0  0  0
 0 -2  0  0
 0  0 -2  0
 0  0  0 -2
[torch.FloatTensor of size 4x4]

In [46]:
a.mul_(c); a


-2  0  0  0
 0 -2  0  0
 0  0 -2  0
 0  0  0 -2
[torch.FloatTensor of size 4x4]

### Média em tensores

In [65]:
a = torch.arange(0,24).view(4,6); a


  0   1   2   3   4   5
  6   7   8   9  10  11
 12  13  14  15  16  17
 18  19  20  21  22  23
[torch.FloatTensor of size 4x6]

In [66]:
u = a.mean(); u

11.5

In [67]:
uu = a.sum()/a.nelement(); uu

11.5

### Média com redução de eixo 

In [73]:
u_row = a.mean(dim=1); u_row


  2.5000
  8.5000
 14.5000
 20.5000
[torch.FloatTensor of size 4]

In [74]:
u_col = a.mean(dim=0); u_col


  9
 10
 11
 12
 13
 14
[torch.FloatTensor of size 6]

### Desvio padrão

In [72]:
std = a.std(); std

7.0710678118654755

In [78]:
std_row = a.std(dim=1); std_row


 1.8708
 1.8708
 1.8708
 1.8708
[torch.FloatTensor of size 4]

## Comparação speedup CPU e GPU

In [54]:
a_cpu = torch.ones(1000,1000)
%timeit b = 2 * a_cpu

431 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
if torch.cuda.is_available():
    a_gpu = a_cpu.cuda()
    %timeit b = 2 * a_gpu

33.7 µs ± 8.76 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Rodando o código abaixo na GTX1080: speedup de 15,5
- 888 µs ± 43.4 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
- 57.1 µs ± 22.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [58]:
%timeit b = a_cpu.mean()
if torch.cuda.is_available():
    %timeit c = a_gpu.mean()

888 µs ± 34.3 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
57 µs ± 92.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
