# Matrizes, Arrays, Tensores

## Referências

- PyTorch para usuários NumPy:
    https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

## NumPy array

In [1]:
import numpy as np

In [21]:
a = np.array([[2., 8., 3.],
              [0.,-1., 5.]])
a

array([[ 2.,  8.,  3.],
       [ 0., -1.,  5.]])

In [22]:
a.shape

(2, 3)

In [23]:
a.dtype

dtype('float64')

## PyTorch tensor

Os tensores do PyTorch só podem ser float, float32 ou float64

In [24]:
import torch

### Convertendo NumPy array para tensor PyTorch

In [25]:
b = torch.Tensor(a)
b


 2  8  3
 0 -1  5
[torch.FloatTensor of size 2x3]

### Criando arrays e tensores constantes

In [27]:
c = np.ones((2,4)); c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [28]:
d = torch.ones((2,4)); d


 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 2x4]

### Criando arrays e tensores aleatórios

In [33]:
e = np.random.rand(2,4); e

array([[ 0.14596948,  0.8078857 ,  0.9871118 ,  0.72366388],
       [ 0.15361686,  0.38709714,  0.30825547,  0.30534131]])

In [34]:
f = torch.rand(2,4); f


 0.3506  0.2202  0.2897  0.9296
 0.1369  0.5075  0.9227  0.7065
[torch.FloatTensor of size 2x4]

### Arrays aleatórios com semente, para reproduzir mesma sequência pseudoaleatória

In [62]:
np.random.seed(1234)
e = np.random.rand(2,4);e

array([[ 0.19151945,  0.62210877,  0.43772774,  0.78535858],
       [ 0.77997581,  0.27259261,  0.27646426,  0.80187218]])

In [54]:
torch.manual_seed(1234)
f = torch.rand(2,4); f


 0.1915  0.4977  0.6221  0.8178
 0.4377  0.6121  0.7854  0.7714
[torch.FloatTensor of size 2x4]

### Torch seed is different for GPU

In [63]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    g = torch.cuda.random.rand(2,4)

## Conversões entre NumPy e Tensores PyTorch

### NumPy para Tensor PyTorch

Não são todos os tipos de elementos do array NumPy que podem ser convertidos 
para tensores PyTorch. Abaixo é um programa que cria uma tabela de equivalencias
entre os tipos do NumPy e os tipos do Tensor PyTorch:

In [155]:
import pandas as pd 
dtypes = [np.uint8, np.int32, np.int64, np.float32, np.float64, np.double]
table = np.empty((2, len(dtypes)),dtype=np.object)
for i,t in enumerate(types):
    a = np.array([1],dtype=t)
    ta = torch.from_numpy(a)
    table[0,i] = a.dtype.name
    table[1,i] = type(ta).__name__
pd.DataFrame(table)

0          1           2            3             4             5
0       uint8      int32       int64      float32       float64       float64
1  ByteTensor  IntTensor  LongTensor  FloatTensor  DoubleTensor  DoubleTensor

In [153]:
table

array([['uint8', 'int32', 'int64', 'float32', 'float64', 'float64', None],
       ['ByteTensor', 'IntTensor', 'LongTensor', 'FloatTensor',
        'DoubleTensor', 'DoubleTensor', None]], dtype=object)

### Tensor PyTorch para array NumPy

In [105]:
ta = torch.ones(2,3)
print(type(ta).__name__)

FloatTensor


In [109]:
a = ta.numpy()
print(type(a).__name__,a.dtype)

ndarray float32


## Tensor na CPU e na GPU

In [110]:
ta_cpu = torch.ones(2,3); ta_cpu


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

In [111]:
if torch.cuda.is_available():
    ta_cpu.cuda()

## Operações em tensores

In [120]:
a = torch.eye(4); a


 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1
[torch.FloatTensor of size 4x4]

In [121]:
a.size()

torch.Size([4, 4])

### Reshape é feito com `view` em PyTorch

In [123]:
b = a.view(2,8); b


    1     0     0     0     0     1     0     0
    0     0     1     0     0     0     0     1
[torch.FloatTensor of size 2x8]

### Adição elemento por elemento

#### usando operadores

In [126]:
c = a + a; c


 2  0  0  0
 0  2  0  0
 0  0  2  0
 0  0  0  2
[torch.FloatTensor of size 4x4]

In [129]:
d = a - c ; d


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

#### forma funcional

In [130]:
d = a.sub(c); d


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

#### Operação in-place

In [131]:
a.sub_(c); a


-1  0  0  0
 0 -1  0  0
 0  0 -1  0
 0  0  0 -1
[torch.FloatTensor of size 4x4]

### Multiplicação elemento por elemento

In [134]:
d = a * c; d 


-2  0  0  0
 0 -2  0  0
 0  0 -2  0
 0  0  0 -2
[torch.FloatTensor of size 4x4]

In [136]:
d = a.mul(c); d


-2  0  0  0
 0 -2  0  0
 0  0 -2  0
 0  0  0 -2
[torch.FloatTensor of size 4x4]

In [139]:
a.mul_(c); a


-8  0  0  0
 0 -8  0  0
 0  0 -8  0
 0  0  0 -8
[torch.FloatTensor of size 4x4]

### Média em tensores

In [141]:
u = a.mean(); u

-2.0

In [144]:
uu = a.sum()/a.(); uu

-16.0