# Redes Neurais Recorrentes

As redes neurais recorrentes são as redes que possuem uma realimentação dos neurônios de saída para a entrada da rede.
A figura a seguir mostra uma rede recorrente simples contendo:
- 2 entradas
- 4 neurônios de saídas
- 1 bias

<img src='../figures/RNN_2_3_4_template.png',width=300pt></img>

Se configurarmos esta rede para processar 3 instantes de tempo (de duas entradas cada), teremos a 
rede equivalente conforme figura a seguir:

<img src='../figures/RNN_2_3_4.png',width=500pt></img>

Note entretanto que os parâmetros da rede são os mesmos para cada instante de tempo.
O número total de parâmetros que precisam ser treinados nesta rede são:
- 2 x 4 = parâmetros da rede de entrada (2 entradas x 4 saídas)
- 4 = bias da rede de entrada (um parâmetro para cada saída)
- 4 x 4 = parâmetros da rede recorrente (4 entradas x 4 saídas)

Este notebook é uma demonstração da construção desta rede utilizando o Keras e valores numérico para poder acompanhar
o processamento da rede recorrente.

## Importação

Iremos exercitar o modelo recorrente mais simples do Keras: `SimpleRNN`

In [1]:
import numpy as np

import torch


In [2]:
batch_size = 1
hidden_units = 4

In [10]:
model = torch.nn.RNN(2, hidden_units, 1)

In [ ]:
model = Sequential()
model.add(SimpleRNN(hidden_units,
                    recurrent_initializer=initializers.Identity(gain=1.0),
                    activation='linear',
                    batch_input_shape= (1, 3, 2),
                    #return_sequences = True,
                    stateful = False,
                    #unroll = True,
                    use_bias=True),
             )

In [11]:
print(model())

TypeError: forward() missing 1 required positional argument: 'input'

## Colocando os parâmetros

### Pesos da rede de entrada

In [9]:
W1_set = np.array([
    [ 1., 2.,  3., 4. ],
    [ 5,  6.,  7., 8]])

### Pesos da rede recorrente

In [ ]:
W2_set = np.array([
    [ 1.,  0.,  0.,  0.],
    [ 0.,  1.,  0.,  0.],
    [ 0.,  0.,  1.,  0.],
    [ 0.,  0.,  0.,  1.]])

### Bias

In [ ]:
W3_set = np.array([ 0.1,  0.2,  0.3,  0.4])

In [6]:
W_set = [W1_set, W2_set,W3_set]
model.set_weights(W_set)

In [7]:
W = model.get_weights()
for Wi in W:
    print(Wi)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[ 0.1         0.2         0.30000001  0.40000001]


In [8]:
x = np.array([[[1,0],[0,0],[0,0]],
              [[1,0],[0,0],[0,0]]])
x.shape

(2, 3, 2)

In [8]:
y = model.predict(x,batch_size=1)
y

array([[ 1.30000007,  2.60000014,  3.89999986,  5.20000029],
       [ 1.30000007,  2.60000014,  3.89999986,  5.20000029]], dtype=float32)

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScvU9jxvImSrQFy0DxV2vJwPGeFZiHquC5x91tdVrMxZJ-vHA/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
