# Getting the data
Keras also offers a collection of datasets that can be used to train and test the model. The MNIST set is a part of the available datasets and can be loaded as shown below.

In [7]:
from keras.datasets import mnist 
# the data, shuffled and split between train and test sets 
(X_train_orig, y_train), (X_test_orig, y_test) = mnist.load_data()

# Reshaping and normalizing the inputs

In [14]:
nb_classes = 10
(M_train,height,width) = X_train_orig.shape  # deve ser 60000 amostras de 28 x 28 pixels
input_dim = height * width
print 'X_train_orig shape original:', X_train_orig.shape
X_train = X_train_orig.reshape(M, input_dim) 
print 'X_train novo shape:', X_train.shape
X_test = X_test_orig.reshape(10000, input_dim) 
X_train = X_train.astype('float32') 
X_test = X_test.astype('float32') 
X_train /= 255 
X_test /= 255

X_train_orig shape original: (60000, 28, 28)
X_train novo shape: (60000, 784)


# Convert class vectors to binary class matrices

In [17]:
from keras.utils import np_utils 
Y_train = np_utils.to_categorical(y_train, nb_classes) 
Y_test = np_utils.to_categorical(y_test, nb_classes)
print y_train[0:5]
print Y_train[0:5]

[5 0 4 1 9]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


# Build the model

In [45]:
from keras.models import Sequential 
from keras.layers import Dense, Activation 
from keras.optimizers import SGD
output_dim = nb_classes = 10 
model = Sequential() 
model.add(Dense(output_dim, input_dim=input_dim, activation='softmax')) 
batch_size = 128
nb_epoch = 20

# Compile the model

Excelente blog sobre otimização:

http://sebastianruder.com/optimizing-gradient-descent/


In [58]:
sgd = SGD(lr=0.01, decay=0e-6, momentum=0., nesterov=False)
model.compile(optimizer=sgd, loss='MSE', metrics=['accuracy']) 
#model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy']) 
history = model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,verbose=2, validation_data=(X_test, Y_test)) 
score = model.evaluate(X_test, Y_test, verbose=0) 
print('Test score:', score[0]) 
print('Test accuracy:', score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
0s - loss: 0.0137 - acc: 0.9116 - val_loss: 0.0131 - val_acc: 0.9166
Epoch 2/20
0s - loss: 0.0137 - acc: 0.9118 - val_loss: 0.0130 - val_acc: 0.9172
Epoch 3/20
0s - loss: 0.0137 - acc: 0.9116 - val_loss: 0.0130 - val_acc: 0.9175
Epoch 4/20
0s - loss: 0.0137 - acc: 0.9117 - val_loss: 0.0130 - val_acc: 0.9172
Epoch 5/20
0s - loss: 0.0137 - acc: 0.9119 - val_loss: 0.0130 - val_acc: 0.9174
Epoch 6/20
0s - loss: 0.0137 - acc: 0.9119 - val_loss: 0.0130 - val_acc: 0.9173
Epoch 7/20
0s - loss: 0.0136 - acc: 0.9120 - val_loss: 0.0130 - val_acc: 0.9173
Epoch 8/20
0s - loss: 0.0136 - acc: 0.9121 - val_loss: 0.0130 - val_acc: 0.9173
Epoch 9/20
0s - loss: 0.0136 - acc: 0.9121 - val_loss: 0.0130 - val_acc: 0.9175
Epoch 10/20
0s - loss: 0.0136 - acc: 0.9122 - val_loss: 0.0130 - val_acc: 0.9174
Epoch 11/20
0s - loss: 0.0136 - acc: 0.9122 - val_loss: 0.0130 - val_acc: 0.9176
Epoch 12/20
0s - loss: 0.0136 - acc: 0.9123 - val_loss: 0.0130 - val