# Getting the data
Keras also offers a collection of datasets that can be used to train and test the model. The MNIST set is a part of the available datasets and can be loaded as shown below.

In [7]:
from keras.datasets import mnist 
# the data, shuffled and split between train and test sets 
(X_train_orig, y_train), (X_test_orig, y_test) = mnist.load_data()

# Reshaping and normalizing the inputs

In [14]:
nb_classes = 10
(M_train,height,width) = X_train_orig.shape  # deve ser 60000 amostras de 28 x 28 pixels
input_dim = height * width
print 'X_train_orig shape original:', X_train_orig.shape
X_train = X_train_orig.reshape(M, input_dim) 
print 'X_train novo shape:', X_train.shape
X_test = X_test_orig.reshape(10000, input_dim) 
X_train = X_train.astype('float32') 
X_test = X_test.astype('float32') 
X_train /= 255 
X_test /= 255

X_train_orig shape original: (60000, 28, 28)
X_train novo shape: (60000, 784)


# Convert class vectors to binary class matrices

In [17]:
from keras.utils import np_utils 
Y_train = np_utils.to_categorical(y_train, nb_classes) 
Y_test = np_utils.to_categorical(y_test, nb_classes)
print y_train[0:5]
print Y_train[0:5]

[5 0 4 1 9]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


# Build the model

In [45]:
from keras.models import Sequential 
from keras.layers import Dense, Activation 
from keras.optimizers import SGD
output_dim = nb_classes = 10 
model = Sequential() 
model.add(Dense(output_dim, input_dim=input_dim, activation='softmax')) 
batch_size = 128
nb_epoch = 20

# Compile the model

Excelente blog sobre otimização:

http://sebastianruder.com/optimizing-gradient-descent/


In [46]:
sgd = SGD(lr=0.01, decay=0e-6, momentum=0., nesterov=False)
model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy']) 
history = model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,verbose=2, validation_data=(X_test, Y_test)) 
score = model.evaluate(X_test, Y_test, verbose=0) 
print('Test score:', score[0]) 
print('Test accuracy:', score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
0s - loss: 1.2596 - acc: 0.6993 - val_loss: 0.8063 - val_acc: 0.8346
Epoch 2/20
0s - loss: 0.7164 - acc: 0.8415 - val_loss: 0.6052 - val_acc: 0.8632
Epoch 3/20
0s - loss: 0.5880 - acc: 0.8604 - val_loss: 0.5243 - val_acc: 0.8734
Epoch 4/20
0s - loss: 0.5262 - acc: 0.8697 - val_loss: 0.4786 - val_acc: 0.8829
Epoch 5/20
0s - loss: 0.4885 - acc: 0.8758 - val_loss: 0.4489 - val_acc: 0.8871
Epoch 6/20
0s - loss: 0.4626 - acc: 0.8802 - val_loss: 0.4274 - val_acc: 0.8909
Epoch 7/20
0s - loss: 0.4433 - acc: 0.8834 - val_loss: 0.4115 - val_acc: 0.8935
Epoch 8/20
0s - loss: 0.4284 - acc: 0.8865 - val_loss: 0.3988 - val_acc: 0.8967
Epoch 9/20
0s - loss: 0.4163 - acc: 0.8885 - val_loss: 0.3883 - val_acc: 0.8985
Epoch 10/20
0s - loss: 0.4063 - acc: 0.8910 - val_loss: 0.3798 - val_acc: 0.9002
Epoch 11/20
0s - loss: 0.3978 - acc: 0.8930 - val_loss: 0.3726 - val_acc: 0.9015
Epoch 12/20
0s - loss: 0.3905 - acc: 0.8946 - val_loss: 0.3661 - val

In [54]:
import numpy as np
a = np.arange(25).reshape((5,5))
print a
a.sum(axis=-2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([50, 55, 60, 65, 70])