# Getting the data
Keras also offers a collection of datasets that can be used to train and test the model. The MNIST set is a part of the available datasets and can be loaded as shown below.

In [59]:
import pandas as pd
from keras.datasets import mnist 
# the data, shuffled and split between train and test sets 
(X_train_orig, y_train), (X_test_orig, y_test) = mnist.load_data()

# Reshaping and normalizing the inputs

In [60]:
nb_classes = 10
(M_train,height,width) = X_train_orig.shape  # deve ser 60000 amostras de 28 x 28 pixels
input_dim = height * width
print 'X_train_orig shape original:', X_train_orig.shape
X_train = X_train_orig.reshape(M, input_dim) 
print 'X_train novo shape:', X_train.shape
X_test = X_test_orig.reshape(10000, input_dim) 
X_train = X_train.astype('float32') 
X_test = X_test.astype('float32') 
X_train /= 255 
X_test /= 255

X_train_orig shape original: (60000, 28, 28)
X_train novo shape: (60000, 784)


# Convert class vectors to binary class matrices

In [61]:
from keras.utils import np_utils 
Y_train = np_utils.to_categorical(y_train, nb_classes) 
Y_test = np_utils.to_categorical(y_test, nb_classes)
print y_train[0:5]
print Y_train[0:5]

[5 0 4 1 9]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


# Build the model

In [62]:
from keras.models import Sequential 
from keras.layers import Dense, Activation 
from keras.optimizers import SGD
output_dim = nb_classes = 10 
model = Sequential() 
model.add(Dense(output_dim, input_dim=input_dim, activation='softmax')) 
batch_size = 128
nb_epoch = 20

# Compile the model

Excelente blog sobre otimização:

http://sebastianruder.com/optimizing-gradient-descent/


In [63]:
sgd = SGD(lr=0.01, decay=0e-6, momentum=0., nesterov=False)
model.compile(optimizer=sgd, loss='MSE', metrics=['accuracy']) 
#model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy']) 
history = model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,verbose=2, validation_data=(X_test, Y_test)) 
score = model.evaluate(X_test, Y_test, verbose=0) 
print('Test score:', score[0]) 
print('Test accuracy:', score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
0s - loss: 0.0886 - acc: 0.1779 - val_loss: 0.0871 - val_acc: 0.2294
Epoch 2/20
0s - loss: 0.0855 - acc: 0.2861 - val_loss: 0.0839 - val_acc: 0.3475
Epoch 3/20
0s - loss: 0.0823 - acc: 0.3856 - val_loss: 0.0806 - val_acc: 0.4240
Epoch 4/20
0s - loss: 0.0790 - acc: 0.4469 - val_loss: 0.0772 - val_acc: 0.4712
Epoch 5/20
0s - loss: 0.0757 - acc: 0.4845 - val_loss: 0.0738 - val_acc: 0.4995
Epoch 6/20
0s - loss: 0.0724 - acc: 0.5105 - val_loss: 0.0706 - val_acc: 0.5244
Epoch 7/20
0s - loss: 0.0693 - acc: 0.5353 - val_loss: 0.0675 - val_acc: 0.5490
Epoch 8/20
0s - loss: 0.0663 - acc: 0.5618 - val_loss: 0.0646 - val_acc: 0.5797
Epoch 9/20
0s - loss: 0.0635 - acc: 0.5906 - val_loss: 0.0618 - val_acc: 0.6105
Epoch 10/20
0s - loss: 0.0609 - acc: 0.6199 - val_loss: 0.0593 - val_acc: 0.6387
Epoch 11/20
0s - loss: 0.0585 - acc: 0.6415 - val_loss: 0.0569 - val_acc: 0.6580
Epoch 12/20
0s - loss: 0.0563 - acc: 0.6590 - val_loss: 0.0547 - val

In [70]:
y_hat = model.predict_classes(X_test)
print y_hat.shape
print y_hat[:5]
print y_test.shape
pd.crosstab(y_hat, y_test)

 9824/10000 [============================>.] - ETA: 0s(10000,)
[7 2 1 0 4]
(10000,)


col_0    0     1    2    3    4    5    6    7    8    9
row_0                                                   
0      917     0   20    8    4  119   24   11   11   22
1        0  1091   40    6   18   44   12   49   43   20
2        8     8  835   32    5   16   17   33   26   12
3        2     3   24  877    2  271    1    1  107   17
4        1     0   11    2  837   32    9   14    5  189
5        0     0    0    0    0   10    0    0    0    0
6       30     6   36   11   44   59  887    6   29    4
7        4     1   22   21    3   60    1  883   16  117
8       15    26   33   34   21  165    7   11  688   30
9        3     0   11   19   48  116    0   20   49  598