# Definição da CNN

In [ ]:
import numpy as np
from keras.models import Model
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D, Input


N = 100
img_rows = 5
img_cols = 5
X_train = np.random.normal(size=[N, 1,img_rows, img_cols])
Y_train = [0]*50 + [1]*50

def get_cnn_model():
    
    inputs = Input((1, img_rows, img_cols))
    conv1 = Convolution2D(1, 1, 1)(inputs)
    actv1 = Activation('relu')(conv1)
    conv2 = Convolution2D(1, 1, 1)(actv1)
    actv1 = Activation('relu')(conv2)
    pool1 = MaxPooling2D(pool_size=(2, 2))(actv1)
    flat = Flatten()(pool1)
    out = Dense(1, activation='sigmoid')(flat)

    model = Model(input=inputs, output=out)
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

# Treino

In [52]:
model = get_cnn_model()
model.fit(X_train, Y_train, batch_size=32, nb_epoch=10, shuffle=True, verbose=1)

Epoch 1/10
100/100 [==============================] - 0s - loss: 0.6931 - acc: 0.4800     
Epoch 2/10
100/100 [==============================] - 0s - loss: 0.6931 - acc: 0.5000     
Epoch 3/10
100/100 [==============================] - 0s - loss: 0.6930 - acc: 0.5400     
Epoch 4/10
100/100 [==============================] - 0s - loss: 0.6929 - acc: 0.5700     
Epoch 5/10
100/100 [==============================] - 0s - loss: 0.6928 - acc: 0.5700     
Epoch 6/10
100/100 [==============================] - 0s - loss: 0.6928 - acc: 0.5700     
Epoch 7/10
100/100 [==============================] - 0s - loss: 0.6927 - acc: 0.5300     
Epoch 8/10
100/100 [==============================] - 0s - loss: 0.6926 - acc: 0.5200     
Epoch 9/10
100/100 [==============================] - 0s - loss: 0.6926 - acc: 0.5400     
Epoch 10/10
100/100 [==============================] - 0s - loss: 0.6925 - acc: 0.5700     


# Teste

In [59]:
X_test = np.random.normal(size=[1,1,img_rows, img_cols])*0.5

print('-'*30)
print "Número de camadas:", len(model.layers)
print('-'*30)

i = 1
for layer in model.layers:
    intermediate_layer_model = Model(input=model.input,output=layer.output)
    intermediate_output = intermediate_layer_model.predict(X_test)
    print('-'*80)
    print "Saída da camada", i, ":", layer
    print('-'*80)
    print intermediate_output
    i+=1
    


------------------------------
Número de camadas: 8
------------------------------
--------------------------------------------------------------------------------
Saída da camada 1 : <keras.engine.topology.InputLayer object at 0x7fea93be1f90>
--------------------------------------------------------------------------------
[[[[-0.66188818 -0.14326166  0.11727178  0.11613194 -0.47778308]
   [ 0.06996645 -0.21665247  0.59013736 -0.37570953  0.47843224]
   [-0.03120828  0.44977975 -0.15224761  0.66348642  0.26922125]
   [ 1.83982038 -0.06529351 -0.65065026  0.45570272 -0.03527046]
   [ 0.52183616  0.75958002  0.47940579  0.82438022 -0.17329875]]]]
--------------------------------------------------------------------------------
Saída da camada 2 : <keras.layers.convolutional.Convolution2D object at 0x7fea93c010d0>
--------------------------------------------------------------------------------
[[[[ -2.36859903e-01  -4.15407717e-02   5.65783158e-02   5.61490431e-02
     -1.67524368e-01]
   