# Truques do NumPY

Entender o funcionamneto do *broadcasting*,  *reshape* e do *axis* do NumPy é muito importante. Nesse tutorial iremos ilustrar esses conceitos através de exemplos. 

## Reshape

In [4]:
import numpy as np

a = np.arange(10)
print "a:"
print a
print "A eh um array unidimensional:", a.shape

a:
[0 1 2 3 4 5 6 7 8 9]
A eh um array unidimensional: (10,)


Podemos utilizar o reshape para "enxergar" o array *a* como um array bidimensional com uma linha:

In [6]:
a = a.reshape(1,-1) # O -1 é uma diretiva para que o NumPy calcule automaticamente as dimensões que faltam
print "a:"
print a
print "A eh um array bidimensional linha:", a.shape

a:
[[0 1 2 3 4 5 6 7 8 9]]
A eh um array bidimensional: (1, 10)


Podemos enxergar o array *a* como um array com uma coluna:

In [8]:
a = a.reshape(-1,1) 
print "a:"
print a
print "A eh um array bidimensional coluna:", a.shape

a:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
A eh um array bidimensional coluna: (10, 1)


O então como um array bidimensional, desde que o número de elementos do array não exceda o número de elementos do array inicial.

In [9]:
a = a.reshape(5,2) 
print "a:"
print a
print "A eh um array bidimensional:", a.shape

a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
A eh um array bidimensional: (5, 2)


## Broadcasting

O broadcasting é uma técnica que permnite a propagação dos valores de um eixo para o outro. Veja o exemplo a seguir onde queremos calcular a potência de todos os elementos do vetor *base* pelos elementos do vetor *exp* e guardar os resultados num array 2D.

In [13]:
exp = np.array([[0,1,2,3,4,5]])
base = np.arange(1,4).reshape(-1,1)

print "Expoentes:"
print exp
print "Base:"
print base

print "Potência:"
print base**exp

Expoentes:
[[0 1 2 3 4 5]]
Base:
[[1]
 [2]
 [3]]
Potência:
[[  1   1   1   1   1   1]
 [  1   2   4   8  16  32]
 [  1   3   9  27  81 243]]


## Axis
Em algumas situações queremos fazer cálculo ou calcular estatísticas ao longo de um eixo. Um array unidimensional possui apenas um eixo (eixo 0), um array bidemensional possui dois eixos (eixos 0 e 1) e assim por diante. Todas as funções do NumPy possuem o parâmetro axis que indica se a operação feita para a função será aplicada ao longo de um eixo. Vejo o exemplo da média abaixo:


In [17]:
a = np.arange(10).reshape(1,-1)
b = np.ones(10).reshape(-1,1)
ab = a + b
print "Array ab:"
print ab
print "Média do array ab:"
print ab.mean()
print "Médias do array ab ao longo das colunas (eixo 1):"
print ab.mean(axis = 1)
print "Médias do array ab ao longo das linhas (eixo 0):"
print ab.mean(axis = 0)

Array ab:
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]
Média do array ab:
5.5
Médias do array ab ao longo das colunas (eixo 1):
[ 5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5]
Médias do array ab ao longo das linhas (eixo 0):
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
