# Truques do NumPy

Entender o funcionamneto do *broadcasting*,  *reshape* e do *axis* do NumPy é muito importante. Nesse tutorial iremos ilustrar esses conceitos através de exemplos. 
 

## Reshape

In [2]:
import numpy as np

a = np.arange(10)
print "a:"
print a
print "A eh um array unidimensional:", a.shape

a:
[0 1 2 3 4 5 6 7 8 9]
A eh um array unidimensional: (10,)


Podemos utilizar o reshape para "enxergar" o array *a* como um array bidimensional com uma linha:

In [3]:
a = a.reshape(1,-1) # O -1 é uma diretiva para que o NumPy calcule automaticamente as dimensões que faltam
print "a:"
print a
print "A eh um array bidimensional linha:", a.shape

a:
[[0 1 2 3 4 5 6 7 8 9]]
A eh um array bidimensional linha: (1, 10)


Podemos enxergar o array *a* como um array com uma coluna:

In [4]:
a = a.reshape(-1,1) 
print "a:"
print a
print "A eh um array bidimensional coluna:", a.shape

a:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
A eh um array bidimensional coluna: (10, 1)


Ou então como um array bidimensional, desde que o número de elementos do array não exceda o número de elementos do array inicial.

In [5]:
a = a.reshape(5,2) 
print "a:"
print a
print "A eh um array bidimensional:", a.shape

a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
A eh um array bidimensional: (5, 2)


Quando se usa o Theano como backend no Keras, o formato de tamanho de entrada dos dados é da forma (profundidade, comprimento, largura). Assim, é necessário que a profundiade seja explicitamente declarada, mesmo que a imagem esteja em tons de cinza, ou seja profundidade igual a 1. Logo, uma dimensão pode ser adicionada ao array sem que seu conteúdo seja alterado usando o reshape. Veja o exemplo:

In [36]:
a = np.arange(10).reshape(2,5)
print "Array",a
print "Tamanho original: ", a.shape

a = a.reshape(1,2,5)

print "Array",a
print "Tamanho modificado (uma dimensão a mais): ", a.shape


Array [[0 1 2 3 4]
 [5 6 7 8 9]]
Tamanho original:  (2, 5)
Array [[[0 1 2 3 4]
  [5 6 7 8 9]]]
Tamanho modificado (uma dimensão a mais):  (1, 2, 5)


## Broadcasting
O broadcasting é uma técnica que permnite a propagação dos valores de um eixo para o outro. Veja o exemplo a seguir onde queremos calcular a potência de todos os elementos do vetor *base* pelos elementos do vetor *exp* e guardar os resultados num array 2D.

In [9]:
exp = np.array([[0,1,2,3,4,5]])
base = np.arange(1,4).reshape(-1,1)

print "Expoentes:"
print exp
print "Tamanho dos expoentes", exp.shape
print "Base:"
print base
print "Tamanho da base", base.shape

print "Potência:"
print base**exp

Expoentes:
[[0 1 2 3 4 5]]
Tamanho dos expoentes (1, 6)
Base:
[[1]
 [2]
 [3]]
Tamanho da base (3, 1)
Potência:
[[  1   1   1   1   1   1]
 [  1   2   4   8  16  32]
 [  1   3   9  27  81 243]]


## Axis
Em algumas situações queremos fazer cálculo ou calcular estatísticas ao longo de um eixo. Um array unidimensional possui apenas um eixo (eixo 0), um array bidimensional possui dois eixos (eixos 0 e 1) e assim por diante. Todas as funções do NumPy possuem o parâmetro axis que indica se a operação feita para a função será aplicada ao longo de um eixo. Vejo o exemplo da média abaixo:


In [10]:
a = np.arange(10).reshape(1,-1)
b = np.ones(10).reshape(-1,1)
ab = a + b
print "Array ab:"
print ab
print "Média do array ab:"
print ab.mean()
print "Médias do array ab ao longo das colunas (eixo 1):"
print ab.mean(axis = 1)
print "Médias do array ab ao longo das linhas (eixo 0):"
print ab.mean(axis = 0)

Array ab:
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]
Média do array ab:
5.5
Médias do array ab ao longo das colunas (eixo 1):
[ 5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5]
Médias do array ab ao longo das linhas (eixo 0):
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


##  Fatiamento (Slicing)

Um recurso importante do numpy é o fatiamento no qual é possível acessar um subconjunto do array de diversas formas. O fatiamento define os índices os quais o array será acessado definindo o ponto inicial, final e o passo entre eles, nesta ordem: [inicial:final:passo].  Todos os 3 parâmetros podem ser opcionais que ocorrem
quando o valor inicial é 0, o valor final é o tamanho do array e o passo é 1. Lembrar que a ordem deles 
é: [inicial:final:passo]. Se o passo for 1 fica: [inicial:final]. Se o início for 0 fica: [:final] e se
o final for o último fica: [inicio:] e se forem todos [:]. Veja alguns exemplos de fatiamento:

In [38]:
a = np.arange(10) 

print "Array:", a         
print "Elementos apartir do índice 2 até o índice menor que o o índice 4 do array:", a[2:4]
print "Elementos apartir do índice 2 até o último índice do array:", a[2:]
print "Elementos até o índice menor que o índice 2 do array:", a[:2]
print "Todos os elementos do array:", a[:]
print "Elementos do array com passo de 2", a[::2]
print "Elementos do array apartir do índice 1 ao 5 com passo de 2", a[1:6:2]

 Array: [0 1 2 3 4 5 6 7 8 9]
Elementos apartir do índice 2 até o índice menor que o o índice 4 do array: [2 3]
Elementos apartir do índice 2 até o último índice do array: [2 3 4 5 6 7 8 9]
Elementos até o índice menor que o índice 2 do array: [0 1]
Todos os elementos do array: [0 1 2 3 4 5 6 7 8 9]
Elementos do array com passo de 2 [0 2 4 6 8]
Elementos do array apartir do índice 1 ao 5 com passo de 2 [1 3 5]


Podemos acessar o array por meio de índices negativos. 

In [39]:
print "Último elemento do array", a[-1]
print "Penúltimo elemento do array", a[-2]
print "Elementos do array até o anti-penúltimo índice do array", a[:-2]
print "Inversão do array", a[::-1]
print "Elementos do array apartir do índice -1 ao -5 com passo de com array invertido", a[-1:-6:-1]
print "Elementos do array apartir do índice -1 ao 5 com passo de com array invertido", a[-1:6:-1]


Último elemento do array 9
Penúltimo elemento do array 8
Elementos do array até o anti-penúltimo índice do array [0 1 2 3 4 5 6 7]
Inversão do array [9 8 7 6 5 4 3 2 1 0]
Elementos do array apartir do índice -1 ao -5 com passo de com array invertido [9 8 7 6 5]
Elementos do array apartir do índice -1 ao 5 com passo de com array invertido [9 8 7]


O mesmo procedimento pode ser feito para earray bidimensionais.

In [49]:
a = np.arange(10).reshape(2,5)

print "Array:", a
print "Elementos da linha de índice 0 e das colunas de índice 0 e 1",  a[:1,:2]
print "Elementos da linha de índice 0",  a[0,:]
print "Elementos da coluna de índice 0",  a[:,0]
print "Elementos das colunas de índice 0 a 1",  a[:,:2]
print "Elementos da última coluna",  a[:,-1]
print "Elementos das coluna de ímdice 1 a 4 com passo 2",  a[:,1:5:2]
print "Elementos das coluna de ímdice -1 a -4 com array invertido",  a[:,-1:-15:-1]



Array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Elementos da linha de índice 0 e das colunas de índice 0 e 1 [[0 1]]
Elementos da linha de índice 0 [0 1 2 3 4]
Elementos da coluna de índice 0 [0 5]
Elementos das colunas de índice 0 a 1 [[0 1]
 [5 6]]
Elementos da última coluna [4 9]
Elementos das coluna de ímdice 1 a 4 com passo 2 [[1 3]
 [6 8]]
Elementos das coluna de ímdice -1 a -4 com array invertido [[4 3 2 1 0]
 [9 8 7 6 5]]
