<img src='../figures/RNN_2_3_4_template.png',width=300pt></img>

<img src='../figures/RNN_2_3_4.png',width=500pt></img>

In [10]:
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import SimpleRNN
from keras import initializers


In [11]:
batch_size = 1
hidden_units = 4



In [107]:
model = Sequential()
model.add(SimpleRNN(hidden_units,
                    #kernel_initializer=initializers.RandomNormal(stddev=0.001),
                    recurrent_initializer=initializers.Identity(gain=1.0),
                    activation='linear',
                    input_shape= (3, 2),
                    use_bias=True),
             )

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_12 (SimpleRNN)    (None, 4)                 28        
Total params: 28
Trainable params: 28
Non-trainable params: 0
_________________________________________________________________
None


In [119]:
model.layers[0].stateful

True

In [120]:
W1_set = np.array([
    [ 1., 2.,  3., 4. ],
    [ 5,  6.,  7., 8]])
W2_set = np.array([
    [ 1.,  0.,  0.,  0.],
    [ 0.,  1.,  0.,  0.],
    [ 0.,  0.,  1.,  0.],
    [ 0.,  0.,  0.,  1.]])
W3_set = np.array([ 0.1,  0.2,  0.3,  0.4])
W_set = [W1_set, W2_set,W3_set]
model.set_weights(W_set)

In [121]:
W = model.get_weights()
#W1: (output,input) Kernel initializer
#W2: (output,output) Recurrent initializer
#W3: (output,) Bias
for Wi in W:
    print(Wi)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[ 0.1         0.2         0.30000001  0.40000001]


In [122]:
x = np.array([[[1,0],[0,0],[0,0]],
              [[0,0],[0,0],[0,0]]])
y = model.predict(x,)
y

array([[ 1.30000007,  2.60000014,  3.89999986,  5.20000029],
       [ 0.30000001,  0.60000002,  0.90000004,  1.20000005]], dtype=float32)

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScvU9jxvImSrQFy0DxV2vJwPGeFZiHquC5x91tdVrMxZJ-vHA/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
